services:
  senaite:
    image: senaite/senaite:2.x
    container_name: senaite_lims
    ports:
      - "8083:8080"
    volumes:
      - senaite-data:/data
    environment:
      - SITE_ID=senaite
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

volumes:
  senaite-data:
    driver: local
